#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = [
    ROOT / "README.md",
    ROOT / ".github" / "SUPPORT.md",
    ROOT / ".github" / "ISSUE_TEMPLATE" / "profile_operations.md",
    *sorted((ROOT / "docs").glob("*.md")),
]

SENSITIVE_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in [
        r"\bcli_[a-z0-9]{8,}",
        r"\bou_[a-z0-9]{8,}",
        r"\boc_[a-z0-9]{8,}",
        r"\bom_[a-z0-9]{8,}",
        r"bytedance\.larkoffice\.com",
        r"\.uploads/",
        r"/Users/bytedance/",
        r"gho_[A-Za-z0-9_]+",
        r"\bsk-(?:proj|live|test|ant|org)-[A-Za-z0-9_-]{12,}",
    ]
]

REQUIRED = {
    "README.md": [
        "Current sponsorware board",
        "docs/sponsorware-board.md",
        "docs/technical-proof-index.md",
        "Sponsor one-pager",
        "docs/sponsor-prospect-pipeline.md",
        "Sponsor prospect pipeline",
        "docs/share-kit.md",
        "sponsor / paid-support intake replies",
        "proof, privacy, support notes",
        "Proof before payment",
        "support/#proof-before-payment",
        "10-second support router",
        "https://happysnaker.github.io/support/#sponsor-router",
        "Tip / Proof / Review / Fund",
        "Deploy read",
        "https://happysnaker.github.io/review/deploy-read-sample/",
        "docs/flagship-technical-map.md",
        "docs/operator-handoff.md",
        "Point-in-time proof snapshot",
        "python3 scripts/check_github_status.py --summary",
        "python3 scripts/run_profile_preflight.py --link-scope core --workers 8 --skip-external",
        "`--json` for machine-readable preflight step status",
        "python3 scripts/check_manual_blockers.py --json",
        "python3 scripts/check_stable_profile_links.py --json",
        "python3 scripts/check_gh_usage.py --json",
        "python3 scripts/check_ci_workflow_contract.py --json",
        "python3 scripts/check_checker_catalog.py --json",
        "Profile CodeQL",
        "qq-ai-bot CodeQL",
        "RDLeader CodeQL",
        "actions/workflows/codeql.yml",
        "qq-ai-bot",
        "RDLeader",
    ],
    ".github/SUPPORT.md": [
        "Proof before payment",
        "10-second support router",
        "support/#sponsor-router",
        "Current concrete asks",
        "Sponsor one-pager",
        "Sponsor / paid-support intake replies",
        "Do not paste private logs, credentials, QR codes, payment screenshots, internal URLs",
        "qq-ai-bot #26 arm64",
        "RDLeader #27",
    ],
    ".github/ISSUE_TEMPLATE/profile_operations.md": [
        "Proof before payment",
        "Current concrete asks",
        "Flagship status snapshot",
        "Share kit / sponsor intake replies",
        "python3 scripts/check_github_status.py",
        "Sponsor / support guardrails",
        "Do not ask for private logs, credentials, QR codes, internal URLs, or payment screenshots in public",
    ],
    "docs/sponsor-one-pager.md": [
        "Point-in-time proof snapshot",
        "before quoting current state",
        "Reproduce this proof packet",
        "python3 scripts/run_profile_preflight.py --link-scope core --workers 8 --skip-external",
        "python3 scripts/check_github_status.py --summary",
        "python3 scripts/check_checker_catalog.py --json",
        "Sponsor prospect pipeline",
        "sponsor-prospect-pipeline.md",
        "Default support fallback",
        "https://github.com/happysnaker/.github/commit/0ec8ed7",
    ],
    "docs/sponsorware-board.md": [
        "Current targets",
        "10-second support router",
        "https://happysnaker.github.io/support/#sponsor-router",
        "Default support fallback",
        "https://github.com/happysnaker/.github/commit/0ec8ed7",
        "47eaa73",
        "Tip / Proof / Review / Fund",
        "Paid support offers",
        "Deploy read",
        "https://happysnaker.github.io/review/deploy-read-sample/",
        "https://happysnaker.github.io/support/#quick-read",
        "¥29.9",
        "¥99",
        "qq-ai-bot #23",
        "RDLeader #2",
        "What sponsorship funds",
    ],
    "docs/flagship-status-snapshot.md": [
        "Flagship GitHub status snapshot",
        "Current support routing",
        "10-second support router",
        "https://happysnaker.github.io/support/#sponsor-router",
        "Current concrete asks",
        "qq-ai-bot #26 arm64",
        "RDLeader #27",
    ],
    "docs/share-kit.md": [
        "Core angle",
        "Audience routing matrix",
        "Homelab / CasaOS tester",
        "Bot / agent builder",
        "Curator / maintainer",
        "Sponsor / funder",
        "GitHub-profile / README customer",
        "Do not say physical ARM / CasaOS validation is complete",
        "Do not repeatedly bump external PRs",
        "Do not request private payment screenshots in public issues",
        "X / short post",
        "LinkedIn / longer post",
        "WeChat / private share",
        "Project-page closed loop update",
        "profile README → project pages",
        "project pages → 10-second support router",
        "Sponsorship CTA snippets",
        "10-second support router ask",
        "https://happysnaker.github.io/support/#sponsor-router",
        "Default support fallback",
        "https://github.com/happysnaker/.github/commit/0ec8ed7",
        "Tip — if one repo saved you time",
        "Fund — if you want a visible public outcome",
        "Deploy-read sample ask",
        "https://happysnaker.github.io/review/deploy-read-sample/",
        "top 3 fixes",
        "qq-ai-bot #26 arm64",
        "RDLeader #27",
        "Guardrails",
        "Sponsor / paid-support intake replies",
        "Before-payment reply",
        "Paid-review intake reply",
        "Sponsor receipt follow-up",
    ],
    "docs/sponsor-prospect-pipeline.md": [
        "Sponsor Prospect Pipeline",
        "Evidence-first pipeline",
        "Do not start from “please donate.”",
        "Coverage ladder",
        "Profile first screen",
        "Public support page",
        "Sponsor release packet",
        "Default account support",
        "Flagship repos",
        "Paid-review repos",
        "Active segments",
        "Homelab / CasaOS / NAS / SBC testers",
        "Bot / agent builders",
        "Curators / maintainers",
        "GitHub profile / README customers",
        "Sponsor / funder",
        "RDLeader evaluators",
        "Backend / systems-study readers",
        "Current working list",
        "qq-ai-bot#26",
        "docker/awesome-compose#781",
        "AwesomeHomelab#98",
        "jbesomi/awesome-autonomous-agents#20",
        "RDLeader#27",
        "2026-07-16 UTC",
        "Proof before payment",
        "10-second support router",
        "Current concrete asks",
        "Deploy-read sample",
        "Tester ask",
        "Paid-review ask",
        "Sponsor ask",
        "Do not claim physical ARM / CasaOS validation is complete",
        "Do not repeatedly bump external PRs before the 2026-07-16 UTC gate",
        "Do not imply reuse rights until `RDLeader#3` and root license posture are resolved",
        "python3 scripts/check_sponsor_pipeline.py --json",
    ],
    "docs/operator-handoff.md": [
        "Current source of truth",
        "python3 scripts/check_github_status.py --summary",
        "python3 scripts/run_profile_preflight.py --link-scope core --workers 8 --skip-external --json",
        "python3 scripts/check_manual_blockers.py --json",
        "Current flagship state",
        "Proof before payment",
        "default funding links include both the root support page and the 10-second support router fallback",
        "Default support fallback: <https://github.com/happysnaker/.github/commit/0ec8ed7> / funding fallback: <https://github.com/happysnaker/.github/commit/47eaa73>",
        "10-second support router: <https://happysnaker.github.io/support/#sponsor-router>",
        "qq-ai-bot #26 arm64",
        "RDLeader#3",
        "External follow-up rule",
        "--enforce-review-due",
        "2026-07-16 UTC",
        "Good next actions",
        "scripts/github_cli.py",
        "stable profile workflow links",
        "one-off profile self-check run links",
        "check_operator_handoff.py",
        "check_stable_profile_links.py --json",
        "check_gh_usage.py --json",
        "check_ci_workflow_contract.py --json",
        "check_checker_catalog.py",
        "check_share_kit.py --json",
        "python3 scripts/check_external_followups.py --action-class optional-update --json",
        "python3 scripts/run_profile_preflight.py --external-only --action-class optional-update --external-candidate-comments --enforce-review-due",
        "--candidate-comments",
        "candidateGuardrails.ok",
        "check_review_funnel.py",
        "Payment screenshot privacy guard",
        "Deploy-read sample",
        "https://happysnaker.github.io/review/deploy-read-sample/",
        "python3 scripts/check_sponsor_issues.py --json",
        "python3 scripts/check_sponsor_release.py --json",
        "python3 scripts/check_ops_issue_log.py --json",
        "python3 scripts/check_public_links.py --scope core --timeout 6 --workers 8 --json",
        "python3 scripts/check_site_hygiene.py --site-root ../happysnaker.github.io --timeout 8 --json",
        "happysnaker#2",
    ],
    "docs/operations-cadence.md": [
        "Machine-readable quick state",
        "python3 scripts/run_profile_preflight.py --link-scope core --workers 8 --json",
        "python3 scripts/check_github_status.py --summary",
        "python3 scripts/check_manual_blockers.py --json",
        "python3 scripts/check_stable_profile_links.py --json",
        "python3 scripts/check_gh_usage.py --json",
        "python3 scripts/check_ci_workflow_contract.py --json",
        "python3 scripts/check_checker_catalog.py --json",
        "--enforce-review-due",
        "python3 scripts/check_review_funnel.py --site-root ../happysnaker.github.io --live --timeout 8 --json",
        "python3 scripts/check_sponsor_issues.py --json",
        "python3 scripts/check_sponsor_release.py --json",
        "10-second support router",
        "support-router fallback",
        "Default funding fallback",
        "https://github.com/happysnaker/.github/commit/47eaa73",
        "python3 scripts/check_support_routes.py --json",
        "python3 scripts/check_repo_metadata.py --json",
        "15 portfolio-critical repository homepages",
        "python3 scripts/check_issue_labels.py --json",
        "python3 scripts/check_readme_badges.py --json",
        "first-screen support/proof routes",
        "python3 scripts/check_ops_issue_log.py --json",
        "python3 scripts/check_public_links.py --scope core --timeout 6 --workers 8 --json",
        "python3 scripts/check_site_hygiene.py --site-root ../happysnaker.github.io --timeout 8 --json",
        "only allowed direct-`gh` script",
        "sponsor / paid-support intake replies",
        "public-privacy guardrails",
    ],
    "docs/manual-github-actions.md": [
        "Pin RDLeader on the profile",
        "replace `Resume` with `RDLeader`",
        "python3 scripts/check_profile_pins.py --strict",
        "Decide RDLeader license posture",
        "python3 scripts/check_rdleader_license.py",
        "Do not imply unrestricted reuse",
        "10-second support router",
        "https://happysnaker.github.io/support/#sponsor-router",
        "Default `.github` funding/support fallback",
        "docs/share-kit.md",
        "scripts/check_issue_labels.py",
        "scripts/check_ops_issue_log.py",
        "happysnaker#2",
    ],
    "docs/portfolio-audit.md": [
        "review / deploy-read funnel",
        "https://happysnaker.github.io/review/",
        "Deploy read",
        "¥29.9",
        "¥99",
        "10-second support router",
        "support/#sponsor-router",
        "funding fallback",
        "check_review_funnel.py",
        "Payment screenshot privacy guard",
        "python3 scripts/check_review_funnel.py --site-root ../happysnaker.github.io --live --timeout 8 --json",
    ],
    "docs/support-surface-coverage.md": [
        "Latest live sponsor/support issue refresh",
        "Latest flagship repo prospect-routing refresh",
        "GitHub readers can route homelab testers, bot builders, curators, sponsors, RDLeader evaluators, and paid-review customers",
        "right proof, CTA, support note, and guardrail",
        "Latest chinese-independent-developer support-intake refresh",
        "Latest indie-list prospect-routing refresh",
        "indie founders, curators, and paid-review buyers",
        "right proof, CTA, support note, and guardrail",
        "e1ec861",
        "Latest go-http-middleware-kit support-intake refresh",
        "Latest Go/database asset prospect-routing refresh",
        "backend-template, middleware, and database-internals buyers",
        "right proof, CTA, support note, and guardrail",
        "48f5954",
        "Latest go-service-starter support-intake refresh",
        "a0d466c",
        "Latest happydb support-intake refresh",
        "493ba48",
        "Latest production-readiness-checklist support-intake refresh",
        "984a08b",
        "Latest system-design-checklist support-intake refresh",
        "5265d50",
        "Latest backend-engineer-checklist support-intake refresh",
        "Latest backend/system/launch prospect-routing refresh",
        "technical-review buyers get the right proof, CTA, support note, and guardrail",
        "3c8e52f",
        "Latest github-profile-checklist support-intake refresh",
        "Latest paid-review prospect-routing refresh",
        "profile, README, resume-site, and landing-page review buyers",
        "right proof, CTA, support note, and guardrail",
        "f173d65",
        "Latest CSAPPLabsAndNotes support-intake refresh",
        "Latest CSAPP prospect-routing refresh",
        "study-repo, README, and technical-profile review requests",
        "e696571",
        "Latest Resume support-intake refresh",
        "bc58edc",
        "Latest support-page sponsor-intake refresh",
        "Latest support-page prospect-routing refresh",
        "sponsor prospect pipeline",
        "proof, CTA, support note, and guardrail",
        "#public-intake-guardrail",
        "31aecf3",
        "qq-ai-bot#28",
        "RDLeader#3",
        "Latest default/profile support-router refresh",
        "Default sponsor prospect pipeline fallback",
        "sponsor prospect pipeline fallback",
        "funding links, plus issue-contact links",
        "support-router defaults",
        "chinese-independent-developer support-intake guardrails",
        "e1ec861",
        "go-http-middleware-kit support-intake guardrails",
        "48f5954",
        "go-service-starter support-intake guardrails",
        "a0d466c",
        "happydb support-intake guardrails",
        "493ba48",
        "production-readiness-checklist support-intake guardrails",
        "984a08b",
        "system-design-checklist support-intake guardrails",
        "5265d50",
        "backend-engineer-checklist support-intake guardrails",
        "3c8e52f",
        "github-profile-checklist support-intake guardrails",
        "f173d65",
        "CSAPPLabsAndNotes support-intake guardrails",
        "e696571",
        "Resume support-intake guardrails",
        "bc58edc",
        "https://github.com/happysnaker/.github/commit/0ec8ed7",
        "Tip / Proof / Review / Fund",
        "Latest project-page sponsor-router refresh",
        "Latest flagship project-page prospect-routing refresh",
        "homelab testers, bot builders, curators, sponsors, RDLeader evaluators, and paid-review customers",
        "right proof, CTA, support note, and guardrail",
        "https://github.com/happysnaker/happysnaker.github.io/commit/843af8d",
        "https://github.com/happysnaker/happysnaker.github.io/actions/runs/29161900218",
        "Pick Tip / Proof / Review / Fund",
        "Latest RDLeader sponsor-router refresh",
        "https://github.com/happysnaker/RDLeader/commit/8e8317a",
        "unresolved license/reuse guardrail",
        "Latest qq-ai-bot sponsor-router refresh",
        "https://github.com/happysnaker/qq-ai-bot/commit/d624e6c",
        "594cb21",
        "10-second support router",
        "choose Tip / Proof / Review / Fund before paying or sponsoring",
        "https://happysnaker.github.io/support/#sponsor-router",
        "Tip / Proof / Review / Fund",
        "deploy-read sample",
        "scripts/check_review_funnel.py",
        "61 remote funding/support/README/issue-contact files",
        "support-router and share-kit routes",
        "sponsor / paid-support intake replies",
        "public-privacy routes",
        "flagship project-page sponsor-intake/privacy markers",
        "support-funnel project-page intake refresh",
        "Systems-study project-page intake guardrails",
        "96b2d00",
        "9eea8b1",
        "1c7d450",
        "b5ddf88",
        "9eea8b1",
        "af2fa9b",
        "69bab33",
        "python3 scripts/check_review_funnel.py --site-root ../happysnaker.github.io --live --timeout 8 --json",
        "python3 scripts/check_site_hygiene.py --site-root ../happysnaker.github.io --live --timeout 8 --json",
        "support anchor integrity",
        "python3 scripts/check_public_links.py --timeout 6 --workers 8 --json",
        "JSON output",
        "Pick the right support path in 10 seconds",
        "support router commit",
        "ed1ecde",
        "e5e44e2",
        "Payment%20screenshot",
        "private email-only `Payment%20screenshot` mailto fields",
        "Latest payment-screenshot privacy refresh",
        "¥29.9",
        "¥99",
        "https://happysnaker.github.io/review/deploy-read-sample/",
        "e9387ce",
        "2b0ad6a",
        "0f13edc",
        "a747985",
        "deploy-read support route",
    ],
    "docs/technical-proof-index.md": [
        "Flagship proof: qq-ai-bot",
        "Flagship proof: RDLeader",
        "Maintenance proof",
        "Sponsorware / support proof",
        "actions/workflows/ci.yml",
        "actions/workflows/codeql.yml",
        "flagship status snapshot",
        "Stable profile proof-link checker",
        "rejects one-off profile self-check run links",
        "stable profile workflow links",
        "scripts/check_stable_profile_links.py",
        "machine-readable proof-link drift state",
        "supports `--json`",
        "--external-candidate-comments",
        "python3 scripts/check_github_status.py",
        "--summary",
        "Shared GitHub CLI helper",
        "GitHub CLI usage checker",
        "scripts/github_cli.py",
        "scripts/check_gh_usage.py",
        "machine-readable helper-usage drift state",
        "expected allowlisted shared helper",
        "missing/unexpected allowlist drift",
        "allowlisted shared helper",
        "total script count",
        "checker catalog JSON",
        "scripts/check_ci_workflow_contract.py",
        "machine-readable workflow-contract drift state",
        "scripts/check_operator_handoff.py",
        "scripts/check_checker_catalog.py",
        "including the catalog checker itself",
        "lacks `--json`",
        "--json",
        "machine-readable link status",
        "the 10-second support router",
        "funding fallback",
        "support-router defaults",
        "chinese-independent-developer support-intake guardrails",
        "e1ec861",
        "go-http-middleware-kit support-intake guardrails",
        "48f5954",
        "go-service-starter support-intake guardrails",
        "a0d466c",
        "happydb support-intake guardrails",
        "493ba48",
        "production-readiness-checklist support-intake guardrails",
        "984a08b",
        "system-design-checklist support-intake guardrails",
        "5265d50",
        "backend-engineer-checklist support-intake guardrails",
        "3c8e52f",
        "github-profile-checklist support-intake guardrails",
        "f173d65",
        "CSAPPLabsAndNotes support-intake guardrails",
        "e696571",
        "Resume support-intake guardrails",
        "bc58edc",
        "sponsor intake fallback",
        "public-privacy guardrails",
        "prepared candidate comments",
        "candidate-comment guardrails",
        "supports `--action-class` filtering, `--json`, `--summary`, and `--candidate-comments`",
        "machine-readable site hygiene status",
        "support anchor integrity",
        "15 portfolio-critical repositories",
        "flagship project-page sponsor-intake/privacy markers",
        "support-funnel project-page intake refresh",
        "Support page sponsor-intake guardrails",
        "#public-intake-guardrail",
        "31aecf3",
        "Support page 10-second sponsor router",
        "#sponsor-router",
        "ed1ecde",
        "e5e44e2",
        "deploy-read sample",
        "a747985",
        "0f13edc",
        "2b0ad6a",
        "b5ddf88",
        "9eea8b1",
        "af2fa9b",
        "69bab33",
    ],
    "docs/upstream-contribution-ledger.md": [
        "Upstream contribution ledger",
        "proof ledger, not a donation page",
        "10-second support router",
        "https://happysnaker.github.io/support/#sponsor-router",
        "do not run `go test` or `go build`",
    ],
    "docs/external-follow-up-queue.md": [
        "Prepared material for the 2026-07-16 review window",
        "Project-page closed loop share snippet",
        "https://happysnaker.github.io/support/#sponsor-router",
        "profile README → project page → 10-second support router",
        "qq-ai-bot still needs a real physical ARM/CasaOS host report",
        "RDLeader reuse rights are still blocked on the license issue",
        "Candidate comments for optional-update rows",
        "docker/awesome-compose#781",
        "AwesomeHomelab#98",
        "jbesomi/awesome-autonomous-agents#20",
        "I am still not claiming real physical ARM/CasaOS completion",
        "Do not post it before the review gate is due",
    ],
    "docs/flagship-technical-map.md": [
        "Fast read",
        "Systems boundary",
        "Operator proof",
        "Maintenance proof",
        "Current support note",
        "Proof before payment",
        "https://happysnaker.github.io/support/#sponsor-router",
        "10-second support router",
        "Deploy read",
        "https://happysnaker.github.io/review/deploy-read-sample/",
        "scripts/check_review_funnel.py",
        "qq-ai-bot #26 arm64",
        "RDLeader #27",
        "Automation that keeps this map honest",
    ],
}

LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def check_file(path: Path) -> None:
    if not path.exists():
        fail(f"missing file: {path.relative_to(ROOT)}")

    text = path.read_text(encoding="utf-8")
    rel = path.relative_to(ROOT).as_posix()

    for line_no, line in enumerate(text.splitlines(), 1):
        if line.rstrip() != line:
            fail(f"{rel}:{line_no}: trailing whitespace")

    for pattern in SENSITIVE_PATTERNS:
        if pattern.search(text):
            fail(f"{rel}: sensitive-looking pattern matched: {pattern.pattern}")

    for needle in REQUIRED.get(rel, []):
        if needle not in text:
            fail(f"{rel}: missing required text: {needle}")

    for link in LINK_RE.findall(text):
        if link.startswith(("http://", "https://", "mailto:", "#")):
            continue
        target_text = link.split("#", 1)[0]
        if not target_text:
            continue
        target = (path.parent / target_text).resolve()
        if not target.exists():
            fail(f"{rel}: broken local link: {link}")


def main() -> None:
    for path in DOCS:
        check_file(path)
    print(f"Verified {len(DOCS)} public markdown files")


if __name__ == "__main__":
    main()
